#!/usr/bin/env python3
"""BUILD-TIME ONLY -- regenerates starry_night/painting_data.py.

The runtime never downloads anything and never reads an image file: the
painting lives inside the generated module as a palette + zlib-compressed
index array. Re-run this only if you want to change the embedded source
art or its resolution.

    python3 tools/embed_painting.py

Requires Pillow (not needed at runtime).
"""
import base64
import os
import subprocess
import textwrap
import zlib

import numpy as np
from PIL import Image

URL = (
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/"
    "Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/"
    "1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg"
)
TARGET_WIDTH = 288
NUM_COLORS = 96

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_PATH = os.path.join(ROOT, "starry_night", "painting_data.py")


def fetch(dest):
    subprocess.run(["curl", "-fsSL", "--max-time", "90", "-o", dest, URL], check=True)


def main():
    tmp = os.path.join(ROOT, "tools", "_painting_source.jpg")
    if not os.path.exists(tmp):
        print(f"downloading {URL}")
        fetch(tmp)

    img = Image.open(tmp).convert("RGB")
    height = round(img.height * TARGET_WIDTH / img.width)
    img = img.resize((TARGET_WIDTH, height), Image.LANCZOS)

    pal_img = img.quantize(colors=NUM_COLORS, method=Image.MEDIANCUT, dither=Image.NONE)
    indices = np.asarray(pal_img, dtype=np.uint8)
    palette = bytes(pal_img.getpalette()[: NUM_COLORS * 3])

    err = np.abs(
        np.asarray(pal_img.convert("RGB"), dtype=float) - np.asarray(img, dtype=float)
    ).mean()

    comp = zlib.compress(indices.tobytes(), 9)
    idx_b64 = base64.b64encode(comp).decode("ascii")
    pal_b64 = base64.b64encode(palette).decode("ascii")

    def as_literal(name, b64):
        lines = "\n".join('    "%s"' % chunk for chunk in textwrap.wrap(b64, 88))
        return f"{name} = (\n{lines}\n)\n"

    parts = [
        '"""Embedded source painting -- GENERATED by tools/embed_painting.py.\n',
        "\n",
        "Van Gogh, *The Starry Night* (1889), public domain. Stored as a\n",
        f"{NUM_COLORS}-color palette plus a zlib-compressed index array so the\n",
        "renderer works completely offline with no image file on disk and no\n",
        f"network access. Mean quantization error: {err:.1f}/255.\n",
        "\n",
        "Do not edit by hand -- re-run the build tool instead.\n",
        '"""\n\n',
        f"WIDTH = {TARGET_WIDTH}\n",
        f"HEIGHT = {height}\n",
        f"NUM_COLORS = {NUM_COLORS}\n\n",
        as_literal("PALETTE_B64", pal_b64),
        "\n",
        as_literal("INDICES_B64", idx_b64),
    ]

    with open(OUT_PATH, "w") as f:
        f.write("".join(parts))

    size_kb = os.path.getsize(OUT_PATH) / 1024
    print(f"wrote {OUT_PATH}")
    print(f"  {TARGET_WIDTH}x{height}, {NUM_COLORS} colors, mean error {err:.1f}/255")
    print(f"  module size: {size_kb:.0f} KB")


if __name__ == "__main__":
    main()
